version: 2
jobs:
  build:
    working_directory: ~/ReactNativeWithTypeScript-CI
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout

      - run: yarn install && yarn tsc

      - run:
          name: Debug Build
          command: ./android/gradlew assembleDebug
